# =====================================================
# APPLICATION
# =====================================================

spring.application.name=order-service
server.port=${PORT:8083}


# =====================================================
# DATABASE - POSTGRESQL
# =====================================================

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# =====================================================
# JPA
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# EUREKA - DISABLED ON RENDER
# =====================================================

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# =====================================================
# SERVICE URLS
# =====================================================

payment.service.url=${PAYMENT_SERVICE_URL}
fund.service.url=${FUND_SERVICE_URL}


# =====================================================
# APPLICATION LOGGING
# =====================================================

logging.level.com.internship.orderservice=INFO