spring.application.name=order-service

server.port=8083


# =====================================================
# DATABASE
# =====================================================

spring.datasource.url=${DB_URL}

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD}


# =====================================================
# JPA
# =====================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# H2 CONSOLE
# =====================================================

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console


# =====================================================
# EUREKA
# =====================================================

eureka.client.service-url.defaultZone=${EUREKA_URL}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=${EUREKA_HOST:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=8083


# =====================================================
# APPLICATION LOGGING
# =====================================================

logging.level.com.internship.orderservice=INFO