# =====================================================
# APPLICATION
# =====================================================

spring.application.name=order-service
server.port=${PORT:8083}


# =====================================================
# DATABASE - POSTGRESQL
# =====================================================

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# =====================================================
# HIKARI CONNECTION POOL
# =====================================================

spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE:5}

spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:1}

spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT:30000}

spring.datasource.hikari.idle-timeout=${DB_IDLE_TIMEOUT:600000}

spring.datasource.hikari.max-lifetime=${DB_MAX_LIFETIME:300000}


# =====================================================
# JPA
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# EUREKA - DISABLED ON RENDER
# =====================================================

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# =====================================================
# SERVICE URLS
# =====================================================

payment.service.url=${PAYMENT_SERVICE_URL}
fund.service.url=${FUND_SERVICE_URL}


# =====================================================
# APPLICATION LOGGING
# =====================================================

logging.level.com.internship.orderservice=INFO

# =====================================================
# BACKGROUND WORKER
# =====================================================

worker.fixed-delay=${WORKER_FIXED_DELAY:5000}